version: '3.8'
services:
  
  server:
    container_name: fastapi
    build: ./backend
    working_dir: /backend
    command: uvicorn main:app --host 0.0.0.0 --reload
    environment:
      DEBUG: 1
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/backend
    ports:
      - 8000:8000
    restart: always
    networks:
      - my_network
  
  # frontend:
  #   container_name: react
  #   build: ./frontend
  #   working_dir: /frontend
  #   volumes:
  #     - ./frontend:/frontend
  #   ports:
  #     - 3000:3000
  #   restart: always
  #   depends_on:
  #     - server
  #   networks:
  #     - my_network
    
networks:
  my_network:
    driver: bridge