version: '3.8'
services:
  
  server:
    build: ./backend
    container_name: server
    restart: always
    ports:
      - "8000:8000"
    volumes:
       - ./backend:/app
    env_file:
      - ./backend/.env
    
      